apiVersion: "cis.f5.com/v1"
kind: IngressLink
metadata:
  name: vs-ingresslink
  namespace: nginx-ingress
spec:
  virtualServerAddress: "10.1.10.100"
  host: cafe.example.com
  iRules:
    - /Common/Proxy_Protocol_iRule
  selector:
    matchLabels:
      app: nginx-ingress